# Generated by Django 4.2.2 on 2023-06-27 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_comment_name_user_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rating',
        ),
        migrations.AddField(
            model_name='food',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food'),
        ),
    ]
