# Generated by Django 4.2.2 on 2023-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_food_rating_food_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(),
        ),
    ]
