# Generated by Django 4.2.2 on 2023-06-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_food_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.food'),
        ),
    ]
