# Generated by Django 4.2.2 on 2023-06-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_comment_name_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
    ]
