# Generated by Django 4.2.2 on 2023-06-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_food_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='avg_rating',
        ),
    ]
