# Generated by Django 4.2.2 on 2023-06-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_alter_comment_name_food_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
