# Generated by Django 4.2.2 on 2023-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
