# Generated by Django 4.2.2 on 2023-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_food_avg_rating_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
